# Concatenate the Metal kernel sources into one C byte array.
#
#   cmake -DVV_OUT=<file.c> -DVV_SRCS=<a.metal;b.metal;...> -P EmbedMetal.cmake
#
# The runtime compiles the text with newLibraryWithSource on first use: the
# offline `metal` compiler ships only with Xcode, and a build machine with
# just the Command Line Tools has to be able to produce a working binary.
# A byte array rather than a string literal, because compilers cap the
# length of a literal and the kernels are well past it.

set(_text "")
foreach(_src IN LISTS VV_SRCS)
    file(READ "${_src}" _body)
    get_filename_component(_name "${_src}" NAME)
    string(APPEND _text "\n#line 1 \"${_name}\"\n${_body}\n")
endforeach()

string(LENGTH "${_text}" _len)
file(WRITE "${VV_OUT}.tmp" "${_text}")
file(READ "${VV_OUT}.tmp" _hex HEX)
file(REMOVE "${VV_OUT}.tmp")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)" "\\1\n" _bytes "${_bytes}")

set(_c "/* Generated by cmake/EmbedMetal.cmake -- do not edit. */\n")
string(APPEND _c "#include <stddef.h>\n")
string(APPEND _c "const char vv_metal_source[] = {\n${_bytes}0x00\n};\n")
string(APPEND _c "const size_t vv_metal_source_len = sizeof(vv_metal_source) - 1;\n")

# Rewrite only when the text changed, so an unchanged kernel set does not
# recompile the runtime.
if(EXISTS "${VV_OUT}")
    file(READ "${VV_OUT}" _old)
    if(_old STREQUAL _c)
        return()
    endif()
endif()
file(WRITE "${VV_OUT}" "${_c}")
